Grammar + more general catching of failures
marigold-dev/breathalyzer pull request #11
Opened 2023-04-04 14:41 UTC by aguillon

![cheh-baker](https://user-images.githubusercontent.com/7795522/229828636-ed7c0ea9-e7f6-40eb-aaac-01170d3d99d6.png)

2023-04-04 15:31 UTC, xvw requested changes

2023-04-04 15:31 UTC, xvw commented on .gitignore
> +.*.sw?
I suggest to move that line into **your** global `gitignore` ;)

2023-04-04 15:31 UTC, xvw commented on lib/expect.mligo
> +  | _ -> Result.fail_with ("Expected failure: `" ^ (Test.to_string message) ^ "`")
Just out of curiosity, why? For me, a message is a string, why not just dealing with `Test.to_string` at the call-site level?

2023-04-05 13:12 UTC, aguillon commented on .gitignore
> +.*.sw?
I could do that, but this .gitignore is already a joke; it might as well contain something useful.

2023-04-05 13:46 UTC, aguillon commented on lib/expect.mligo
> +  | _ -> Result.fail_with ("Expected failure: `" ^ (Test.to_string message) ^ "`")
I've considered changing the name of the function to `fail_with_value` but this would break the many many projects that use Batcher. In any case, several of these projects (Batcher, Checker…) use integer error codes and it doesn't seem useful to me to treat strings as a specific case.

2023-04-05 13:50 UTC, xvw commented on lib/expect.mligo
> +  | _ -> Result.fail_with ("Expected failure: `" ^ (Test.to_string message) ^ "`")
WDYT of having both ? Fail with value and fail with message (that use fail with value)

2023-04-05 14:06 UTC, merged